import React, { useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import SectionWrapper from '../components/SectionWrapper.jsx';

const PrivaciyPolicy = () => {
	const location = useLocation();

	useEffect(() => {
		if (location.hash) {
			const id = location.hash.replace('#', '');
			const el = document.getElementById(id);
			if (el) {
				setTimeout(() => {
					const header = document.querySelector('.header');
					const headerHeight = header ? header.getBoundingClientRect().height : 0;
					const extraOffset = 12; // small gap below header
					const top = window.pageYOffset + el.getBoundingClientRect().top - headerHeight - extraOffset;
					window.scrollTo({ top: Math.max(0, Math.round(top)), behavior: 'smooth' });
				}, 60);
			}
		}
	}, [location]);

	return (
		<>
			<SectionWrapper id="privacy" title="Privacy Policy" eyebrow="Privacy & Terms" subtitle="Effective Date: 26.12.2025">
				<h3>Privacy Policy</h3>
				<p>
					AIzantra Intelligence Private Limited (“AIzantra”, “we”, “our”) provides consulting,
					advisory, software products, and technology services. This Privacy Policy describes how we
					collect, use, and protect personal data through our website www.aizantraintelligence.com.
					This policy complies with applicable Indian laws including the Information Technology Act,
					2000, SPDI Rules (2011), and the Digital Personal Data Protection Act, 2023.
				</p>

				<h4>Information We Collect</h4>
				<ul>
					<li>Business contact details (name, email, phone, organization)</li>
					<li>Information submitted via forms or communications</li>
					<li>Limited technical information automatically generated by website infrastructure for security and performance purposes</li>
				</ul>

				<h4>Purpose of Use</h4>
				<p>Data is used to:</p>
				<ul>
					<li>Respond to inquiries and business requests</li>
					<li>Provide consulting services and software products</li>
					<li>Operate, improve, and secure our website</li>
					<li>Meet legal and regulatory obligations</li>
				</ul>

				<h4>Data Sharing</h4>
				<p>We do not sell personal data. Data may be shared only with authorized service providers or as required by law.</p>

				<h4>Data Security &amp; Retention</h4>
				<p>Reasonable security safeguards are applied. Data is retained only as necessary for business or legal purposes.</p>

				<h4>Your Rights</h4>
				<p>
					You may request access, correction, deletion, or withdrawal of consent as permitted under Indian law.
				</p>

				<h4>Grievance Officer</h4>
				<p>
					Email: <a href="mailto:contact@aizantraintelligence.com">contact@aizantraintelligence.com</a>
				</p>
				<p>Responses will be provided within statutory timelines.</p>

				<hr />

					<div id="terms" className="terms-section">
						<h3>Terms of Service</h3>
						<p><strong>Effective Date:</strong> 26-12-2025</p>
						<p>
							These Terms govern access to www.aizantraintelligence.com, operated by AIzantra Intelligence
							Private Limited. By using this website, you agree to these Terms.
						</p>

						<h4>Use of Website</h4>
						<p>
							The website provides general information about AIzantra’s consulting services and software
							products. Content does not constitute professional advice.
						</p>

						<h4>Intellectual Property</h4>
						<p>
							All website content, trademarks, and materials are owned by AIzantra unless stated otherwise.
							Unauthorized use is prohibited.
						</p>

						<h4>Engagement Terms</h4>
						<p>
							Consulting services and software products are governed by separate written agreements. Website
							content does not create any binding obligation.
						</p>

						<h4>Limitation of Liability</h4>
						<p>
							To the extent permitted by law, AIzantra shall not be liable for indirect or consequential damages arising from website use.
						</p>

						<h4>Governing Law</h4>
						<p>
							These Terms are governed by the laws of India. Courts in [Insert City] shall have exclusive jurisdiction.
						</p>
					</div>

				<h4>Contact</h4>
				<p>Email: <a href="mailto:contact@aizantraintelligence.com">contact@aizantraintelligence.com</a></p>
			</SectionWrapper>
		</>
	);
};

export default PrivaciyPolicy;
