import React, { useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import SectionWrapper from '../components/SectionWrapper.jsx';

const PrivaciyPolicy = () => {
	const location = useLocation();

	useEffect(() => {
		if (location.hash) {
			const id = location.hash.replace('#', '');
			const el = document.getElementById(id);
			if (el) {
				setTimeout(() => {
					const header = document.querySelector('.header');
					const headerHeight = header ? header.getBoundingClientRect().height : 0;
					const extraOffset = 12; // small gap below header
					const top = window.pageYOffset + el.getBoundingClientRect().top - headerHeight - extraOffset;
					window.scrollTo({ top: Math.max(0, Math.round(top)), behavior: 'smooth' });
				}, 60);
			}
		}
	}, [location]);

	return (
		<>
			<SectionWrapper id="privacy"
			title={<span style={{ color: '#f97316' }}>Privacy Policy</span>}
			// eyebrow={<span style={{ color: '#1f2937' }}>Privacy and Terms</span>}
			subtitle="Effective Date: 26.12.2025">
					{/* <h3>Privacy Policy</h3> */}
					<p className="big-para">
					AIzantra Intelligence Private Limited (“AIzantra”, “we”, “our”) provides consulting,
					advisory, software products, and technology services. This Privacy Policy describes how we
					collect, use, and protect personal data through our website www.aizantraintelligence.com.
					This policy complies with applicable Indian laws including the Information Technology Act,
					2000, SPDI Rules (2011), and the Digital Personal Data Protection Act, 2023.
				</p>
				<br />
				<h4 className="big-para">Information We Collect</h4>
				<ul className="big-para" style={{ color: '#4d5765' }}>
					<li>Business contact details (name, email, phone, organization)</li>
					<li>Information submitted via forms or communications</li>
					<li>Limited technical information automatically generated by website infrastructure for security and performance purposes</li>
				</ul>
				<br />

				<h4 className="big-para">Purpose of Use</h4>
				<p className="big-para">Data is used to:</p>
				<ul className="big-para" style={{ color: '#4d5765' }}>
					<li>Respond to inquiries and business requests</li>
					<li>Provide consulting services and software products</li>
					<li>Operate, improve, and secure our website</li>
					<li>Meet legal and regulatory obligations</li>
				</ul>
				<br />

				<h4 className="big-para">Data Sharing</h4>
				<p className="big-para">We do not sell personal data. Data may be shared only with authorized service providers or as required by law.</p>
				<br />

				<h4 className="big-para">Data Security &amp; Retention</h4>
				<p className="big-para">Reasonable security safeguards are applied. Data is retained only as necessary for business or legal purposes.</p>
				<br />

				<h4 className="big-para">Your Rights</h4>
				<p className="big-para">
					You may request access, correction, deletion, or withdrawal of consent as permitted under Indian law.
				</p>
				<br />

				<h4 className="big-para">Grievance Officer</h4>
				<p className="big-para">
					Email: <a href="mailto:contact@aizantraintelligence.com">contact@aizantraintelligence.com</a>
				</p>
				<p className="big-para">Responses will be provided within statutory timelines.</p>
				<br />

				<hr />

				<br />
				<h4 className="big-para">Contact</h4>
				<p className="big-para">Email: <a href="mailto:contact@aizantraintelligence.com">contact@aizantraintelligence.com</a></p>
			</SectionWrapper>
		</>
	);
};

export default PrivaciyPolicy;
